Repository SWE3022-42-team9/skktudy-server, pull requests merged in 2023-11, with the labels that each got.

#10 Implement comment_like
  modules/comment.py
Labels: enhancement

#12 db.py models import 수정
  util/db.py
Labels: bug

#14 라우팅 HTTP method 설정
  app.py
Labels: bug, enhancement

#13 Implement /board/<board_id>
  app.py
  modules/board.py
  util/db.py
Labels: enhancement

#15 Implement /post/like
  app.py
  modules/post.py
  util/db.py
Labels: enhancement

#16 Implement comment.py
  modules/comment.py
Labels: enhancement

#17 Implement /post/<post_id>
  app.py
  modules/post.py
  util/db.py
  util/models.py
Labels: enhancement

#24 Fix/models table
  .gitignore
  util/db.py
  util/models.py
Labels: bug

#25 Implement post_upload function in post.py
  modules/post.py
  util/db.py
Labels: enhancement

#30 /post/<post_id> 로직 함수 오타 수정
  modules/post.py
Labels: bug

#34 Remove unnecessary parameter of post_get function
  modules/post.py
Labels: bug

#18 Routing function 일부 구현
  app.py
Labels: enhancement

#32 implement initial chatbot flow and app.py
  AI/.gitignore
  AI/.streamlit/config.toml
  AI/.vscode/launch.json
  AI/LICENSE
  AI/README.md
  AI/requirements.txt
  AI/src/app.py
  AI/src/chatbot.py
  AI/src/client.py
  AI/src/output_parsers.py
  AI/src/templates.py
  app.py
  modules/chatbot.py
Labels: enhancement

#37 uwsgi 구성 파일 및 서버 실행 파일
  app.ini
  start_deploy.sh
  start_dev.sh
Labels: enhancement

#35 Fix db_url to use environment variables
  util/db.py
Labels: enhancement

#38 Remove cd statements in bash
  start_deploy.sh
  start_dev.sh
Labels: bug

#39 AI 디렉토리 내 import 문 수정
  AI/src/app.py
  AI/src/chatbot.py
Labels: bug

#11 Implement /board
  app.py
  modules/board.py
  util/db.py
Labels: enhancement

#26 토큰 인증 관련 기능 구현
  .gitignore
  app.py
  modules/auth.py
  requirements.txt
  util/db.py
Labels: enhancement

#28 토큰 불필요 API 처리
  app.py
  modules/board.py
  modules/post.py
Labels: enhancement

#29 DB 참조 시 uid 대신 유저 이름 반환
  util/db.py
Labels: bug

#36 /board 및 /post/upload routing 함수 구현
  app.py
Labels: enhancement

#33 PR #23 복구(#24로 인한 삭제)
  .gitignore
  util/db.py
Labels: bug

#46 import 없이 SQLAlchemyError 사용 수정
  modules/post.py
Labels: bug

#48 게시판이 하나도 없을 시 항상 에러를 반환하는 오류 수정
  modules/board.py
Labels: bug

#49 bash 파일 parameter 수정
  start_deploy.sh
  start_dev.sh
Labels: bug

#50 토큰 검증 강화
  app.py
Labels: enhancement

#51 좋아요 갯수 반환 추가
  modules/board.py
  modules/post.py
  util/db.py
Labels: enhancement

#52 댓글을 시간 순으로 정렬
  util/db.py
Labels: bug

#59 Fix wrong loop range in board_get
  modules/board.py
Labels: bug

#58 좋아요 계산 코드 수정
  modules/board.py
  modules/post.py
Labels: bug

#60 get_board_posts 리턴 타입 수정
  util/db.py
Labels: bug

#61 psutil.virtual.memory() 오타 수정
  modules/chatbot.py
Labels: bug

#62 POST 데이터 참조 불가 오류 수정
  app.py
Labels: bug

#63 라우팅 함수의 예측 불가한 에러 로깅 구문 추가
  app.py
Labels: enhancement

#64 이메일 사용자를 위한 익명 이름 생성
  modules/auth.py
Labels: enhancement

#65 db.py의 잘못된 리턴 타입 수정 및 사용법 수정
  modules/board.py
  modules/post.py
  util/db.py
Labels: bug
